---
all:
  hosts:
    ubuntu-recovered:
      ansible_ssh_host: 10

ubuntu-servers:
  hosts:
    ubuntu-recovered
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common: '-o StrictHostKeyCheckingansible_host=no'



dev-servers:
  hosts:
    ubuntu-recovered
  vars:
    ansible_ssh_private_key_file: 
